### PR TITLE
MEN-6425: Only update device inventory when changed

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by merlin-northern** [comment]
@mender-test-bot start pipeline please

**Comment by merlin-northern** [comment]
@alfrunes this code fails the tests not by accident.
```
time="2023-08-29T18:46:03Z" level=error msg="internal error: failed to replace attributes in db: (ConflictingUpdateOperators) Updating the path 'attributes.inventory-device_type' would create a conflict at 'attributes.inventory-device_type'" device_id=d5316d76-7342-409c-89c7-51b9710a0206 file=response_helpers.go func=rest_utils.restErrWithLogMsg line=110 plan=enterprise request_id=7695212a-4ac7-4ebd-a960-0739fa7d85df
time="2023-08-29T18:46:03Z" level=info msg="500 2443μs PUT /api/0.1.0/attributes HTTP/1.1 - Go-http-client/1.1" byteswritten=78 device_id=d5316d76-7342-409c-89c7-51b9710a0206 file=middleware.go func="accesslog.(*AccessLogMiddleware).MiddlewareFunc.func1" line=82 method=PUT path=/api/0.1.0/attributes plan=enterprise qs= request_id=7695212a-4ac7-4ebd-a960-0739fa7d85df responsetime=0.002443567 status=500 ts="2023-08-29 18:46:03.42231308 +0000 UTC" type=http
```

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline

**Comment by alfrunes** [comment]
@merlin-northern I fixed the deduplication issue and rebased the PR on top of master. I also added a couple of commits for optimizing the limits computation.

**Comment by alfrunes** [comment]
@mender-test-bot start pipeline please

**Comment by tranchitella** [comment]
I want to replace this PR with https://github.com/mendersoftware/inventory/pull/409

**Comment by tranchitella** [comment]
-

**Pull request closed without merging**
