### PR TITLE
docs/devices: use correct device attributes endpoint

### PR DESCRIPTION
**Pull request by bboozzoo**
Gateway configuration maps /api/devices/0.1/inventory/device/attributes
to /api/0.1.0/attributes.

See: https://github.com/mendersoftware/mender-api-gateway-docker/blob/master/nginx.conf#L86

@maciejmrowiec @mchalski @kjaskiewiczz @marekswiecznik

### CODE REVIEW

**Comment by maciejmrowiec** [comment]
This will break integration, is there a PR for gateway ?

**Comment by bboozzoo** [comment]
Documentation is incorrect. The gateway is already setup this way.

**Comment by maciejmrowiec** [comment]
gateway routes now: `rewrite ^.*$ /api/0.1.0/attributes break;` this PR changes target route this to ` /api/0.1.0/device/attributes` so routing will break or am I missing something ?

**Comment by bboozzoo** [comment]
I don't follow, what target route change? There's no change. The PR updates the documentation about the user/device facing API to list the correct endpoint. The one listed there is incorrect and you get 404 right away.

**Comment by maciejmrowiec** [comment]
ugh, Monday syndrome :/

**Comment by maciejmrowiec** [comment]
thanks

**Pull request merged**
